#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// Audio - XIAO ESP32S3 Sense has built-in PDM microphone
#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// PDM Microphone (built-in)
#define AUDIO_I2S_PDM_MIC
#define AUDIO_I2S_MIC_GPIO_CLK  GPIO_NUM_42  // PDM CLK
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_41  // PDM DATA

// External I2S Speaker - using MAX98357A or similar I2S amplifier
// Connect: BCLK→GPIO1, LRC→GPIO2, DIN→GPIO3, VIN→3.3V, GND→GND
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_1   // I2S BCLK
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_2   // I2S LRCK/WS
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_3   // I2S DATA OUT

#define BUILTIN_LED_GPIO        GPIO_NUM_21
#define BOOT_BUTTON_GPIO        GPIO_NUM_0

// XIAO ESP32S3 Sense Camera Pins
#define CAMERA_PIN_D0    GPIO_NUM_15
#define CAMERA_PIN_D1    GPIO_NUM_17
#define CAMERA_PIN_D2    GPIO_NUM_18
#define CAMERA_PIN_D3    GPIO_NUM_16
#define CAMERA_PIN_D4    GPIO_NUM_14
#define CAMERA_PIN_D5    GPIO_NUM_12
#define CAMERA_PIN_D6    GPIO_NUM_11
#define CAMERA_PIN_D7    GPIO_NUM_48
#define CAMERA_PIN_XCLK  GPIO_NUM_10
#define CAMERA_PIN_PCLK  GPIO_NUM_13
#define CAMERA_PIN_VSYNC GPIO_NUM_38
#define CAMERA_PIN_HREF  GPIO_NUM_47
#define CAMERA_PIN_SIOC  GPIO_NUM_39
#define CAMERA_PIN_SIOD  GPIO_NUM_40
#define CAMERA_PIN_PWDN  GPIO_NUM_NC
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define XCLK_FREQ_HZ     20000000

// Display - connect external SPI display
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_MOSI_PIN      GPIO_NUM_9
#define DISPLAY_CLK_PIN       GPIO_NUM_7
#define DISPLAY_DC_PIN        GPIO_NUM_4
#define DISPLAY_RST_PIN       GPIO_NUM_5
#define DISPLAY_CS_PIN        GPIO_NUM_2

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0

#endif
